# Section A: Data Structures & Control Structures

In [1]:
#creating a list of 5 integers.

list_1 = [3,2,1,4,5]

#append operation
append_operation = list_1.append(6)
print('After Append')
print(list_1)

#extend operation
list_extnd = [7,10]
extend_operation = list_1.extend(list_extnd)
print('After Extend')
print(list_1)

#insert operation
insert_operation = list_1.insert(4,6)
print('After Insert')
print(list_1)

#remove operation
remove_operation = list_1.remove(10)
print('After Remove')
print(list_1)

#pop operation
pop_operation = list_1.pop()
print('After Pop')
print(list_1)

#index operation
index_operation = list_1.index(1)
print('After Index')
print(index_operation)

#count operation
count_operation = list_1.count(6)
print('After Count')
print(count_operation)

#sort operation
sort_operation = list_1.sort()
print('After Sorting')
print(list_1)

#Reverse operation
reverse_operation = list_1.reverse()
print('After Reverse')
print(list_1)

#Clear Operation
clear_operation = list_1.clear()
print('After Clear')
print(list_1)

After Append
[3, 2, 1, 4, 5, 6]
After Extend
[3, 2, 1, 4, 5, 6, 7, 10]
After Insert
[3, 2, 1, 4, 6, 5, 6, 7, 10]
After Remove
[3, 2, 1, 4, 6, 5, 6, 7]
After Pop
[3, 2, 1, 4, 6, 5, 6]
After Index
2
After Count
2
After Sorting
[1, 2, 3, 4, 5, 6, 6]
After Reverse
[6, 6, 5, 4, 3, 2, 1]
After Clear
[]


In [2]:
#creating a tuple
tuple_1 = ('Sugar', 'Bugs Bunny', 'Sweet Pea')

#Answer
print('\n')
print("Answer: In a tuple, we cannot change the elements because it is immutable which means once the tuple is created, you cannot alter it's elements. But if we really want to change the elements then there is an indirect method. First we can convert the tuple to list, change the element using list operation and change it back into a tuple.")
print('\n')
print("In conclusion, we do not have a direct way to change the element of tuple.")
print('\n')
print('Below is the method how we can convert the tuple to a list, change the element and convert it back to a tuple.')

#converting this to a list
new_list = list(tuple_1)
new_list[1] = "Chickpea"

#convert this new list, back into a tuple
new_tuple = tuple(new_list)
print('\n')
print('original Tuple:', tuple_1)
print('new Tuple:',new_tuple)



Answer: In a tuple, we cannot change the elements because it is immutable which means once the tuple is created, you cannot alter it's elements. But if we really want to change the elements then there is an indirect method. First we can convert the tuple to list, change the element using list operation and change it back into a tuple.


In conclusion, we do not have a direct way to change the element of tuple.


Below is the method how we can convert the tuple to a list, change the element and convert it back to a tuple.


original Tuple: ('Sugar', 'Bugs Bunny', 'Sweet Pea')
new Tuple: ('Sugar', 'Chickpea', 'Sweet Pea')


In [3]:
#creating a set using set function
sample_set = set([1,2,2,2,3,3,4,5,6,6,6])
print(sample_set)
print('\n')
print("A set removes the duplicate values and returns only the unique elements.")

{1, 2, 3, 4, 5, 6}


A set removes the duplicate values and returns only the unique elements.


In [4]:
new_dict = {'name': 'Bugs Bunny', 'age': 28, 'city': 'Coimbatore'}
print('Initial Dictionary')
print(new_dict)

#Updating the age and adding new key 'email'
new_dict['age'] = 30
new_dict['email'] = 'bugs.bunny@mail.com'
print('\n')
print('Final Dictionary')
print(new_dict)


Initial Dictionary
{'name': 'Bugs Bunny', 'age': 28, 'city': 'Coimbatore'}


Final Dictionary
{'name': 'Bugs Bunny', 'age': 30, 'city': 'Coimbatore', 'email': 'bugs.bunny@mail.com'}


In [5]:
age = int(input('Enter your age: '))
print(age)
if age >= 18:
    print('Eligible for Voting')
else:
    print('Not Eligible for voting.')

Enter your age: 14
14
Not Eligible for voting.


In [6]:
marks = int(input('Enter your marks: '))
print(marks)

if marks >= 90:
    print('A grade')
elif marks>=75 and marks<=89:
    print('B grade')
elif marks>=50 and marks<=74:
    print('C grade')
elif marks<50:
     print('Fail')
else:
    print('Enter the correct details.')

Enter your marks: 67
67
C grade


In [8]:
number = int(input('Enter your number: '))

if number > 0:
    if number%2 == 0:
        print(number, "is positive and even.")
    elif number%2 !=0:
        print(number, "is positive but not even. It's an Odd number.")
    elif number == 0:
        print('Number is Zero')
    elif number < 0:
        print('Number is Negative')
    else:
        print('The data entered is not right')

Enter your number: 89
89 is positive but not even. It's an Odd number.


# Section B: Numpy

In [10]:
import numpy as np

#creating a scalar 
scalar = np.array(5)
print(scalar)
print(type(scalar))
print('\n')

#create a 1D array with values 1 to 5
array_1 = np.arange(1,6)
print('One-D Array:',array_1)
print('\n')

#create a 2D array with values from 10 to 60 in steps of 10
array_2 = np.arange(10, 61, 10)
new_array = array_2.reshape(2,3)
print('Two-D Array:',new_array)

5
<class 'numpy.ndarray'>


One-D Array: [1 2 3 4 5]


Two-D Array: [[10 20 30]
 [40 50 60]]


In [12]:
list = np.random.randint(0,101,16)
arr = np.array(list)
reshaped_array = arr.reshape(4,4)
print(reshaped_array)

[[77 10 19 37]
 [36 98 88 26]
 [94 89 90 56]
 [49 99 96  4]]


In [18]:
import pandas as pd
array_of_elements = np.random.randint(1,50,(3,3))
df = pd.DataFrame(array_of_elements, columns=['A','B','C'])
print(array_of_elements)
print("---------------")
print(df)

[[29 45 35]
 [16 19 21]
 [48 26 23]]
---------------
    A   B   C
0  29  45  35
1  16  19  21
2  48  26  23


# Section C: Exploring Pandas

In [20]:
data_set = {
    'Name': ['Alia','Meerab','Fatima','Omar','Aisha','Dawood','Zara','Ali','Noah'],
    'Age': [25,30,28,22,35,40,29,25,31],
    'City': ['Delhi','Mumbai','Delhi','Chennai','Delhi','Bangalore','Mumbai','Delhi','Chennai'],
    'Salary': [50000,60000,None,45000,70000,52000,80000,50000,62000]
}

df_dataset = pd.DataFrame(data_set)

print(df_dataset)

     Name  Age       City   Salary
0    Alia   25      Delhi  50000.0
1  Meerab   30     Mumbai  60000.0
2  Fatima   28      Delhi      NaN
3    Omar   22    Chennai  45000.0
4   Aisha   35      Delhi  70000.0
5  Dawood   40  Bangalore  52000.0
6    Zara   29     Mumbai  80000.0
7     Ali   25      Delhi  50000.0
8    Noah   31    Chennai  62000.0
